export const regencies = [
  {
    type: "Kabupaten",
    regency: "Aceh Barat",
    province_code: 11,
    code: 1105,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Barat Daya",
    province_code: 11,
    code: 1112,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Besar",
    province_code: 11,
    code: 1106,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Jaya",
    province_code: 11,
    code: 1114,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Selatan",
    province_code: 11,
    code: 1101,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Singkil",
    province_code: 11,
    code: 1110,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Tamiang",
    province_code: 11,
    code: 1116,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Tengah",
    province_code: 11,
    code: 1104,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Tenggara",
    province_code: 11,
    code: 1102,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Timur",
    province_code: 11,
    code: 1103,
  },
  {
    type: "Kabupaten",
    regency: "Aceh Utara",
    province_code: 11,
    code: 1108,
  },
  {
    type: "Kabupaten",
    regency: "Agam",
    province_code: 13,
    code: 1306,
  },
  {
    type: "Kabupaten",
    regency: "Alor",
    province_code: 53,
    code: 5305,
  },
  {
    type: "Kota",
    regency: "Ambon",
    province_code: 81,
    code: 8171,
  },
  {
    type: "Kabupaten",
    regency: "Asahan",
    province_code: 12,
    code: 1209,
  },
  {
    type: "Kabupaten",
    regency: "Asmat",
    province_code: 93,
    code: 9304,
  },
  {
    type: "Kabupaten",
    regency: "Badung",
    province_code: 51,
    code: 5103,
  },
  {
    type: "Kabupaten",
    regency: "Balangan",
    province_code: 63,
    code: 6311,
  },
  {
    type: "Kota",
    regency: "Balikpapan",
    province_code: 64,
    code: 6471,
  },
  {
    type: "Kota",
    regency: "Banda Aceh",
    province_code: 11,
    code: 1171,
  },
  {
    type: "Kota",
    regency: "Bandar Lampung",
    province_code: 18,
    code: 1871,
  },
  {
    type: "Kota",
    regency: "Bandung",
    province_code: 32,
    code: 3273,
  },
  {
    type: "Kabupaten",
    regency: "Bandung",
    province_code: 32,
    code: 3204,
  },
  {
    type: "Kabupaten",
    regency: "Bandung Barat",
    province_code: 32,
    code: 3217,
  },
  {
    type: "Kabupaten",
    regency: "Banggai",
    province_code: 72,
    code: 7201,
  },
  {
    type: "Kabupaten",
    regency: "Banggai Kepulauan",
    province_code: 72,
    code: 7207,
  },
  {
    type: "Kabupaten",
    regency: "Banggai Laut",
    province_code: 72,
    code: 7211,
  },
  {
    type: "Kabupaten",
    regency: "Bangka",
    province_code: 19,
    code: 1901,
  },
  {
    type: "Kabupaten",
    regency: "Bangka Barat",
    province_code: 19,
    code: 1905,
  },
  {
    type: "Kabupaten",
    regency: "Bangka Selatan",
    province_code: 19,
    code: 1903,
  },
  {
    type: "Kabupaten",
    regency: "Bangka Tengah",
    province_code: 19,
    code: 1904,
  },
  {
    type: "Kabupaten",
    regency: "Bangkalan",
    province_code: 35,
    code: 3526,
  },
  {
    type: "Kabupaten",
    regency: "Bangli",
    province_code: 51,
    code: 5106,
  },
  {
    type: "Kota",
    regency: "Banjar",
    province_code: 32,
    code: 3279,
  },
  {
    type: "Kabupaten",
    regency: "Banjar",
    province_code: 63,
    code: 6303,
  },
  {
    type: "Kota",
    regency: "Banjarbaru",
    province_code: 63,
    code: 6372,
  },
  {
    type: "Kota",
    regency: "Banjarmasin",
    province_code: 63,
    code: 6371,
  },
  {
    type: "Kabupaten",
    regency: "Banjarnegara",
    province_code: 33,
    code: 3304,
  },
  {
    type: "Kabupaten",
    regency: "Bantaeng",
    province_code: 73,
    code: 7303,
  },
  {
    type: "Kabupaten",
    regency: "Bantul",
    province_code: 34,
    code: 3402,
  },
  {
    type: "Kabupaten",
    regency: "Banyuasin",
    province_code: 16,
    code: 1607,
  },
  {
    type: "Kabupaten",
    regency: "Banyumas",
    province_code: 33,
    code: 3302,
  },
  {
    type: "Kabupaten",
    regency: "Banyuwangi",
    province_code: 35,
    code: 3510,
  },
  {
    type: "Kabupaten",
    regency: "Barito Kuala",
    province_code: 63,
    code: 6304,
  },
  {
    type: "Kabupaten",
    regency: "Barito Selatan",
    province_code: 62,
    code: 6204,
  },
  {
    type: "Kabupaten",
    regency: "Barito Timur",
    province_code: 62,
    code: 6213,
  },
  {
    type: "Kabupaten",
    regency: "Barito Utara",
    province_code: 62,
    code: 6205,
  },
  {
    type: "Kabupaten",
    regency: "Barru",
    province_code: 73,
    code: 7311,
  },
  {
    type: "Kota",
    regency: "Batam",
    province_code: 21,
    code: 2171,
  },
  {
    type: "Kabupaten",
    regency: "Batang",
    province_code: 33,
    code: 3325,
  },
  {
    type: "Kabupaten",
    regency: "Batanghari",
    province_code: 15,
    code: 1504,
  },
  {
    type: "Kota",
    regency: "Batu",
    province_code: 35,
    code: 3579,
  },
  {
    type: "Kabupaten",
    regency: "Batu Bara",
    province_code: 12,
    code: 1219,
  },
  {
    type: "Kota",
    regency: "Bau Bau",
    province_code: 74,
    code: 7472,
  },
  {
    type: "Kota",
    regency: "Bekasi",
    province_code: 32,
    code: 3275,
  },
  {
    type: "Kabupaten",
    regency: "Bekasi",
    province_code: 32,
    code: 3216,
  },
  {
    type: "Kabupaten",
    regency: "Belitung",
    province_code: 19,
    code: 1902,
  },
  {
    type: "Kabupaten",
    regency: "Belitung Timur",
    province_code: 19,
    code: 1906,
  },
  {
    type: "Kabupaten",
    regency: "Belu",
    province_code: 53,
    code: 5304,
  },
  {
    type: "Kabupaten",
    regency: "Bener Meriah",
    province_code: 11,
    code: 1117,
  },
  {
    type: "Kabupaten",
    regency: "Bengkalis",
    province_code: 14,
    code: 1403,
  },
  {
    type: "Kabupaten",
    regency: "Bengkayang",
    province_code: 61,
    code: 6107,
  },
  {
    type: "Kota",
    regency: "Bengkulu",
    province_code: 17,
    code: 1771,
  },
  {
    type: "Kabupaten",
    regency: "Bengkulu Selatan",
    province_code: 17,
    code: 1701,
  },
  {
    type: "Kabupaten",
    regency: "Bengkulu Tengah",
    province_code: 17,
    code: 1709,
  },
  {
    type: "Kabupaten",
    regency: "Bengkulu Utara",
    province_code: 17,
    code: 1703,
  },
  {
    type: "Kabupaten",
    regency: "Berau",
    province_code: 64,
    code: 6403,
  },
  {
    type: "Kabupaten",
    regency: "Biak Numfor",
    province_code: 91,
    code: 9106,
  },
  {
    type: "Kabupaten",
    regency: "Bima",
    province_code: 52,
    code: 5206,
  },
  {
    type: "Kota",
    regency: "Bima",
    province_code: 52,
    code: 5272,
  },
  {
    type: "Kota",
    regency: "Binjai",
    province_code: 12,
    code: 1275,
  },
  {
    type: "Kabupaten",
    regency: "Bintan",
    province_code: 21,
    code: 2101,
  },
  {
    type: "Kabupaten",
    regency: "Bireuen",
    province_code: 11,
    code: 1111,
  },
  {
    type: "Kota",
    regency: "Bitung",
    province_code: 71,
    code: 7172,
  },
  {
    type: "Kabupaten",
    regency: "Blitar",
    province_code: 35,
    code: 3505,
  },
  {
    type: "Kota",
    regency: "Blitar",
    province_code: 35,
    code: 3572,
  },
  {
    type: "Kabupaten",
    regency: "Blora",
    province_code: 33,
    code: 3316,
  },
  {
    type: "Kabupaten",
    regency: "Boalemo",
    province_code: 75,
    code: 7502,
  },
  {
    type: "Kabupaten",
    regency: "Bogor",
    province_code: 32,
    code: 3201,
  },
  {
    type: "Kota",
    regency: "Bogor",
    province_code: 32,
    code: 3271,
  },
  {
    type: "Kabupaten",
    regency: "Bojonegoro",
    province_code: 35,
    code: 3522,
  },
  {
    type: "Kabupaten",
    regency: "Bolaang Mongondow",
    province_code: 71,
    code: 7101,
  },
  {
    type: "Kabupaten",
    regency: "Bolaang Mongondow Selatan",
    province_code: 71,
    code: 7111,
  },
  {
    type: "Kabupaten",
    regency: "Bolaang Mongondow Timur",
    province_code: 71,
    code: 7110,
  },
  {
    type: "Kabupaten",
    regency: "Bolaang Mongondow Utara",
    province_code: 71,
    code: 7108,
  },
  {
    type: "Kabupaten",
    regency: "Bombana",
    province_code: 74,
    code: 7406,
  },
  {
    type: "Kabupaten",
    regency: "Bondowoso",
    province_code: 35,
    code: 3511,
  },
  {
    type: "Kabupaten",
    regency: "Bone",
    province_code: 73,
    code: 7308,
  },
  {
    type: "Kabupaten",
    regency: "Bone Bolango",
    province_code: 75,
    code: 7503,
  },
  {
    type: "Kota",
    regency: "Bontang",
    province_code: 64,
    code: 6474,
  },
  {
    type: "Kabupaten",
    regency: "Boven Digoel",
    province_code: 93,
    code: 9302,
  },
  {
    type: "Kabupaten",
    regency: "Boyolali",
    province_code: 33,
    code: 3309,
  },
  {
    type: "Kabupaten",
    regency: "Brebes",
    province_code: 33,
    code: 3329,
  },
  {
    type: "Kota",
    regency: "Bukittinggi",
    province_code: 13,
    code: 1375,
  },
  {
    type: "Kabupaten",
    regency: "Buleleng",
    province_code: 51,
    code: 5108,
  },
  {
    type: "Kabupaten",
    regency: "Bulukumba",
    province_code: 73,
    code: 7302,
  },
  {
    type: "Kabupaten",
    regency: "Bulungan",
    province_code: 65,
    code: 6501,
  },
  {
    type: "Kabupaten",
    regency: "Bungo",
    province_code: 15,
    code: 1508,
  },
  {
    type: "Kabupaten",
    regency: "Buol",
    province_code: 72,
    code: 7205,
  },
  {
    type: "Kabupaten",
    regency: "Buru",
    province_code: 81,
    code: 8104,
  },
  {
    type: "Kabupaten",
    regency: "Buru Selatan",
    province_code: 81,
    code: 8109,
  },
  {
    type: "Kabupaten",
    regency: "Buton",
    province_code: 74,
    code: 7404,
  },
  {
    type: "Kabupaten",
    regency: "Buton Selatan",
    province_code: 74,
    code: 7415,
  },
  {
    type: "Kabupaten",
    regency: "Buton Tengah",
    province_code: 74,
    code: 7414,
  },
  {
    type: "Kabupaten",
    regency: "Buton Utara",
    province_code: 74,
    code: 7410,
  },
  {
    type: "Kabupaten",
    regency: "Ciamis",
    province_code: 32,
    code: 3207,
  },
  {
    type: "Kabupaten",
    regency: "Cianjur",
    province_code: 32,
    code: 3203,
  },
  {
    type: "Kabupaten",
    regency: "Cilacap",
    province_code: 33,
    code: 3301,
  },
  {
    type: "Kota",
    regency: "Cilegon",
    province_code: 36,
    code: 3672,
  },
  {
    type: "Kota",
    regency: "Cimahi",
    province_code: 32,
    code: 3277,
  },
  {
    type: "Kota",
    regency: "Cirebon",
    province_code: 32,
    code: 3274,
  },
  {
    type: "Kabupaten",
    regency: "Cirebon",
    province_code: 32,
    code: 3209,
  },
  {
    type: "Kabupaten",
    regency: "Dairi",
    province_code: 12,
    code: 1211,
  },
  {
    type: "Kabupaten",
    regency: "Deiyai",
    province_code: 94,
    code: 9408,
  },
  {
    type: "Kabupaten",
    regency: "Deli Serdang",
    province_code: 12,
    code: 1207,
  },
  {
    type: "Kabupaten",
    regency: "Demak",
    province_code: 33,
    code: 3321,
  },
  {
    type: "Kota",
    regency: "Denpasar",
    province_code: 51,
    code: 5171,
  },
  {
    type: "Kota",
    regency: "Depok",
    province_code: 32,
    code: 3276,
  },
  {
    type: "Kabupaten",
    regency: "Dharmasraya",
    province_code: 13,
    code: 1310,
  },
  {
    type: "Kabupaten",
    regency: "Dogiyai",
    province_code: 94,
    code: 9406,
  },
  {
    type: "Kabupaten",
    regency: "Dompu",
    province_code: 52,
    code: 5205,
  },
  {
    type: "Kabupaten",
    regency: "Donggala",
    province_code: 72,
    code: 7203,
  },
  {
    type: "Kota",
    regency: "Dumai",
    province_code: 14,
    code: 1472,
  },
  {
    type: "Kabupaten",
    regency: "Empat Lawang",
    province_code: 16,
    code: 1611,
  },
  {
    type: "Kabupaten",
    regency: "Ende",
    province_code: 53,
    code: 5308,
  },
  {
    type: "Kabupaten",
    regency: "Enrekang",
    province_code: 73,
    code: 7316,
  },
  {
    type: "Kabupaten",
    regency: "Fak Fak",
    province_code: 92,
    code: 9203,
  },
  {
    type: "Kabupaten",
    regency: "Flores Timur",
    province_code: 53,
    code: 5306,
  },
  {
    type: "Kabupaten",
    regency: "Garut",
    province_code: 32,
    code: 3205,
  },
  {
    type: "Kabupaten",
    regency: "Gayo Lues",
    province_code: 11,
    code: 1113,
  },
  {
    type: "Kabupaten",
    regency: "Gianyar",
    province_code: 51,
    code: 5104,
  },
  {
    type: "Kabupaten",
    regency: "Gorontalo",
    province_code: 75,
    code: 7501,
  },
  {
    type: "Kota",
    regency: "Gorontalo",
    province_code: 75,
    code: 7571,
  },
  {
    type: "Kabupaten",
    regency: "Gorontalo Utara",
    province_code: 75,
    code: 7505,
  },
  {
    type: "Kabupaten",
    regency: "Gowa",
    province_code: 73,
    code: 7306,
  },
  {
    type: "Kabupaten",
    regency: "Gresik",
    province_code: 35,
    code: 3525,
  },
  {
    type: "Kabupaten",
    regency: "Grobogan",
    province_code: 33,
    code: 3315,
  },
  {
    type: "Kabupaten",
    regency: "Gunung Mas",
    province_code: 62,
    code: 6210,
  },
  {
    type: "Kabupaten",
    regency: "Gunungkidul",
    province_code: 34,
    code: 3403,
  },
  {
    type: "Kota",
    regency: "Gunungsitoli",
    province_code: 12,
    code: 1278,
  },
  {
    type: "Kabupaten",
    regency: "Halmahera Barat",
    province_code: 82,
    code: 8201,
  },
  {
    type: "Kabupaten",
    regency: "Halmahera Selatan",
    province_code: 82,
    code: 8204,
  },
  {
    type: "Kabupaten",
    regency: "Halmahera Tengah",
    province_code: 82,
    code: 8202,
  },
  {
    type: "Kabupaten",
    regency: "Halmahera Timur",
    province_code: 82,
    code: 8206,
  },
  {
    type: "Kabupaten",
    regency: "Halmahera Utara",
    province_code: 82,
    code: 8203,
  },
  {
    type: "Kabupaten",
    regency: "Hulu Sungai Selatan",
    province_code: 63,
    code: 6306,
  },
  {
    type: "Kabupaten",
    regency: "Hulu Sungai Tengah",
    province_code: 63,
    code: 6307,
  },
  {
    type: "Kabupaten",
    regency: "Hulu Sungai Utara",
    province_code: 63,
    code: 6308,
  },
  {
    type: "Kabupaten",
    regency: "Humbang Hasundutan",
    province_code: 12,
    code: 1216,
  },
  {
    type: "Kabupaten",
    regency: "Indragiri Hilir",
    province_code: 14,
    code: 1404,
  },
  {
    type: "Kabupaten",
    regency: "Indragiri Hulu",
    province_code: 14,
    code: 1402,
  },
  {
    type: "Kabupaten",
    regency: "Indramayu",
    province_code: 32,
    code: 3212,
  },
  {
    type: "Kabupaten",
    regency: "Intan Jaya",
    province_code: 94,
    code: 9407,
  },
  {
    type: "Kota",
    regency: "Jakarta Barat",
    province_code: 31,
    code: 3173,
  },
  {
    type: "Kota",
    regency: "Jakarta Pusat",
    province_code: 31,
    code: 3171,
  },
  {
    type: "Kota",
    regency: "Jakarta Selatan",
    province_code: 31,
    code: 3174,
  },
  {
    type: "Kota",
    regency: "Jakarta Timur",
    province_code: 31,
    code: 3175,
  },
  {
    type: "Kota",
    regency: "Jakarta Utara",
    province_code: 31,
    code: 3172,
  },
  {
    type: "Kota",
    regency: "Jambi",
    province_code: 15,
    code: 1571,
  },
  {
    type: "Kabupaten",
    regency: "Jayapura",
    province_code: 91,
    code: 9103,
  },
  {
    type: "Kota",
    regency: "Jayapura",
    province_code: 91,
    code: 9171,
  },
  {
    type: "Kabupaten",
    regency: "Jayawijaya",
    province_code: 95,
    code: 9501,
  },
  {
    type: "Kabupaten",
    regency: "Jember",
    province_code: 35,
    code: 3509,
  },
  {
    type: "Kabupaten",
    regency: "Jembrana",
    province_code: 51,
    code: 5101,
  },
  {
    type: "Kabupaten",
    regency: "Jeneponto",
    province_code: 73,
    code: 7304,
  },
  {
    type: "Kabupaten",
    regency: "Jepara",
    province_code: 33,
    code: 3320,
  },
  {
    type: "Kabupaten",
    regency: "Jombang",
    province_code: 35,
    code: 3517,
  },
  {
    type: "Kabupaten",
    regency: "Kaimana",
    province_code: 92,
    code: 9208,
  },
  {
    type: "Kabupaten",
    regency: "Kampar",
    province_code: 14,
    code: 1401,
  },
  {
    type: "Kabupaten",
    regency: "Kapuas",
    province_code: 62,
    code: 6203,
  },
  {
    type: "Kabupaten",
    regency: "Kapuas Hulu",
    province_code: 61,
    code: 6106,
  },
  {
    type: "Kabupaten",
    regency: "Karanganyar",
    province_code: 33,
    code: 3313,
  },
  {
    type: "Kabupaten",
    regency: "Karangasem",
    province_code: 51,
    code: 5107,
  },
  {
    type: "Kabupaten",
    regency: "Karawang",
    province_code: 32,
    code: 3215,
  },
  {
    type: "Kabupaten",
    regency: "Karimun",
    province_code: 21,
    code: 2102,
  },
  {
    type: "Kabupaten",
    regency: "Karo",
    province_code: 12,
    code: 1206,
  },
  {
    type: "Kabupaten",
    regency: "Katingan",
    province_code: 62,
    code: 6206,
  },
  {
    type: "Kabupaten",
    regency: "Kaur",
    province_code: 17,
    code: 1704,
  },
  {
    type: "Kabupaten",
    regency: "Kayong Utara",
    province_code: 61,
    code: 6111,
  },
  {
    type: "Kabupaten",
    regency: "Kebumen",
    province_code: 33,
    code: 3305,
  },
  {
    type: "Kabupaten",
    regency: "Kediri",
    province_code: 35,
    code: 3506,
  },
  {
    type: "Kota",
    regency: "Kediri",
    province_code: 35,
    code: 3571,
  },
  {
    type: "Kabupaten",
    regency: "Keerom",
    province_code: 91,
    code: 9111,
  },
  {
    type: "Kabupaten",
    regency: "Kendal",
    province_code: 33,
    code: 3324,
  },
  {
    type: "Kota",
    regency: "Kendari",
    province_code: 74,
    code: 7471,
  },
  {
    type: "Kabupaten",
    regency: "Kepahiang",
    province_code: 17,
    code: 1708,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Anambas",
    province_code: 21,
    code: 2105,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Aru",
    province_code: 81,
    code: 8107,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Mentawai",
    province_code: 13,
    code: 1309,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Meranti",
    province_code: 14,
    code: 1410,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Sangihe",
    province_code: 71,
    code: 7103,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Selayar",
    province_code: 73,
    code: 7301,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Seribu",
    province_code: 31,
    code: 3101,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Siau Tagulandang Biaro (Sitaro)",
    province_code: 71,
    code: 7109,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Sula",
    province_code: 82,
    code: 8205,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Talaud",
    province_code: 71,
    code: 7104,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Tanimbar (Maluku Tenggara Barat)",
    province_code: 81,
    code: 8103,
  },
  {
    type: "Kabupaten",
    regency: "Kepulauan Yapen",
    province_code: 91,
    code: 9105,
  },
  {
    type: "Kabupaten",
    regency: "Kerinci",
    province_code: 15,
    code: 1501,
  },
  {
    type: "Kabupaten",
    regency: "Ketapang",
    province_code: 61,
    code: 6104,
  },
  {
    type: "Kabupaten",
    regency: "Klaten",
    province_code: 33,
    code: 3310,
  },
  {
    type: "Kabupaten",
    regency: "Klungkung",
    province_code: 51,
    code: 5105,
  },
  {
    type: "Kabupaten",
    regency: "Kolaka",
    province_code: 74,
    code: 7401,
  },
  {
    type: "Kabupaten",
    regency: "Kolaka Timur",
    province_code: 74,
    code: 7411,
  },
  {
    type: "Kabupaten",
    regency: "Kolaka Utara",
    province_code: 74,
    code: 7408,
  },
  {
    type: "Kabupaten",
    regency: "Konawe",
    province_code: 74,
    code: 7402,
  },
  {
    type: "Kabupaten",
    regency: "Konawe Kepulauan",
    province_code: 74,
    code: 7412,
  },
  {
    type: "Kabupaten",
    regency: "Konawe Selatan",
    province_code: 74,
    code: 7405,
  },
  {
    type: "Kabupaten",
    regency: "Konawe Utara",
    province_code: 74,
    code: 7409,
  },
  {
    type: "Kabupaten",
    regency: "Kotabaru",
    province_code: 63,
    code: 6302,
  },
  {
    type: "Kota",
    regency: "Kotamobagu",
    province_code: 71,
    code: 7174,
  },
  {
    type: "Kabupaten",
    regency: "Kotawaringin Barat",
    province_code: 62,
    code: 6201,
  },
  {
    type: "Kabupaten",
    regency: "Kotawaringin Timur",
    province_code: 62,
    code: 6202,
  },
  {
    type: "Kabupaten",
    regency: "Kuantan Singingi",
    province_code: 14,
    code: 1409,
  },
  {
    type: "Kabupaten",
    regency: "Kubu Raya",
    province_code: 61,
    code: 6112,
  },
  {
    type: "Kabupaten",
    regency: "Kudus",
    province_code: 33,
    code: 3319,
  },
  {
    type: "Kabupaten",
    regency: "Kulon Progo",
    province_code: 34,
    code: 3401,
  },
  {
    type: "Kabupaten",
    regency: "Kuningan",
    province_code: 32,
    code: 3208,
  },
  {
    type: "Kabupaten",
    regency: "Kupang",
    province_code: 53,
    code: 5301,
  },
  {
    type: "Kota",
    regency: "Kupang",
    province_code: 53,
    code: 5371,
  },
  {
    type: "Kabupaten",
    regency: "Kutai Barat",
    province_code: 64,
    code: 6407,
  },
  {
    type: "Kabupaten",
    regency: "Kutai Kartanegara",
    province_code: 64,
    code: 6402,
  },
  {
    type: "Kabupaten",
    regency: "Kutai Timur",
    province_code: 64,
    code: 6408,
  },
  {
    type: "Kabupaten",
    regency: "Labuhanbatu",
    province_code: 12,
    code: 1210,
  },
  {
    type: "Kabupaten",
    regency: "Labuhanbatu Selatan",
    province_code: 12,
    code: 1222,
  },
  {
    type: "Kabupaten",
    regency: "Labuhanbatu Utara",
    province_code: 12,
    code: 1223,
  },
  {
    type: "Kabupaten",
    regency: "Lahat",
    province_code: 16,
    code: 1604,
  },
  {
    type: "Kabupaten",
    regency: "Lamandau",
    province_code: 62,
    code: 6209,
  },
  {
    type: "Kabupaten",
    regency: "Lamongan",
    province_code: 35,
    code: 3524,
  },
  {
    type: "Kabupaten",
    regency: "Lampung Barat",
    province_code: 18,
    code: 1804,
  },
  {
    type: "Kabupaten",
    regency: "Lampung Selatan",
    province_code: 18,
    code: 1801,
  },
  {
    type: "Kabupaten",
    regency: "Lampung Tengah",
    province_code: 18,
    code: 1802,
  },
  {
    type: "Kabupaten",
    regency: "Lampung Timur",
    province_code: 18,
    code: 1807,
  },
  {
    type: "Kabupaten",
    regency: "Lampung Utara",
    province_code: 18,
    code: 1803,
  },
  {
    type: "Kabupaten",
    regency: "Landak",
    province_code: 61,
    code: 6108,
  },
  {
    type: "Kabupaten",
    regency: "Langkat",
    province_code: 12,
    code: 1205,
  },
  {
    type: "Kota",
    regency: "Langsa",
    province_code: 11,
    code: 1174,
  },
  {
    type: "Kabupaten",
    regency: "Lanny Jaya",
    province_code: 95,
    code: 9507,
  },
  {
    type: "Kabupaten",
    regency: "Lebak",
    province_code: 36,
    code: 3602,
  },
  {
    type: "Kabupaten",
    regency: "Lebong",
    province_code: 17,
    code: 1707,
  },
  {
    type: "Kabupaten",
    regency: "Lembata",
    province_code: 53,
    code: 5313,
  },
  {
    type: "Kota",
    regency: "Lhokseumawe",
    province_code: 11,
    code: 1173,
  },
  {
    type: "Kabupaten",
    regency: "Lima Puluh Kota",
    province_code: 13,
    code: 1307,
  },
  {
    type: "Kabupaten",
    regency: "Lingga",
    province_code: 21,
    code: 2104,
  },
  {
    type: "Kabupaten",
    regency: "Lombok Barat",
    province_code: 52,
    code: 5201,
  },
  {
    type: "Kabupaten",
    regency: "Lombok Tengah",
    province_code: 52,
    code: 5202,
  },
  {
    type: "Kabupaten",
    regency: "Lombok Timur",
    province_code: 52,
    code: 5203,
  },
  {
    type: "Kabupaten",
    regency: "Lombok Utara",
    province_code: 52,
    code: 5208,
  },
  {
    type: "Kota",
    regency: "Lubuk Linggau",
    province_code: 16,
    code: 1673,
  },
  {
    type: "Kabupaten",
    regency: "Lumajang",
    province_code: 35,
    code: 3508,
  },
  {
    type: "Kabupaten",
    regency: "Luwu",
    province_code: 73,
    code: 7317,
  },
  {
    type: "Kabupaten",
    regency: "Luwu Timur",
    province_code: 73,
    code: 7324,
  },
  {
    type: "Kabupaten",
    regency: "Luwu Utara",
    province_code: 73,
    code: 7322,
  },
  {
    type: "Kabupaten",
    regency: "Madiun",
    province_code: 35,
    code: 3519,
  },
  {
    type: "Kota",
    regency: "Madiun",
    province_code: 35,
    code: 3577,
  },
  {
    type: "Kabupaten",
    regency: "Magelang",
    province_code: 33,
    code: 3308,
  },
  {
    type: "Kota",
    regency: "Magelang",
    province_code: 33,
    code: 3371,
  },
  {
    type: "Kabupaten",
    regency: "Magetan",
    province_code: 35,
    code: 3520,
  },
  {
    type: "Kabupaten",
    regency: "Mahakam Ulu",
    province_code: 64,
    code: 6411,
  },
  {
    type: "Kabupaten",
    regency: "Majalengka",
    province_code: 32,
    code: 3210,
  },
  {
    type: "Kabupaten",
    regency: "Majene",
    province_code: 76,
    code: 7605,
  },
  {
    type: "Kota",
    regency: "Makassar",
    province_code: 73,
    code: 7371,
  },
  {
    type: "Kabupaten",
    regency: "Malaka",
    province_code: 53,
    code: 5321,
  },
  {
    type: "Kabupaten",
    regency: "Malang",
    province_code: 35,
    code: 3507,
  },
  {
    type: "Kota",
    regency: "Malang",
    province_code: 35,
    code: 3573,
  },
  {
    type: "Kabupaten",
    regency: "Malinau",
    province_code: 65,
    code: 6502,
  },
  {
    type: "Kabupaten",
    regency: "Maluku Barat Daya",
    province_code: 81,
    code: 8108,
  },
  {
    type: "Kabupaten",
    regency: "Maluku Tengah",
    province_code: 81,
    code: 8101,
  },
  {
    type: "Kabupaten",
    regency: "Maluku Tenggara",
    province_code: 81,
    code: 8102,
  },
  {
    type: "Kabupaten",
    regency: "Mamasa",
    province_code: 76,
    code: 7603,
  },
  {
    type: "Kabupaten",
    regency: "Mamberamo Raya",
    province_code: 91,
    code: 9120,
  },
  {
    type: "Kabupaten",
    regency: "Mamberamo Tengah",
    province_code: 95,
    code: 9505,
  },
  {
    type: "Kabupaten",
    regency: "Mamuju",
    province_code: 76,
    code: 7602,
  },
  {
    type: "Kabupaten",
    regency: "Mamuju Tengah",
    province_code: 76,
    code: 7606,
  },
  {
    type: "Kota",
    regency: "Manado",
    province_code: 71,
    code: 7171,
  },
  {
    type: "Kabupaten",
    regency: "Mandailing Natal",
    province_code: 12,
    code: 1213,
  },
  {
    type: "Kabupaten",
    regency: "Manggarai",
    province_code: 53,
    code: 5310,
  },
  {
    type: "Kabupaten",
    regency: "Manggarai Barat",
    province_code: 53,
    code: 5315,
  },
  {
    type: "Kabupaten",
    regency: "Manggarai Timur",
    province_code: 53,
    code: 5319,
  },
  {
    type: "Kabupaten",
    regency: "Manokwari",
    province_code: 92,
    code: 9202,
  },
  {
    type: "Kabupaten",
    regency: "Manokwari Selatan",
    province_code: 92,
    code: 9211,
  },
  {
    type: "Kabupaten",
    regency: "Mappi",
    province_code: 93,
    code: 9303,
  },
  {
    type: "Kabupaten",
    regency: "Maros",
    province_code: 73,
    code: 7309,
  },
  {
    type: "Kota",
    regency: "Mataram",
    province_code: 52,
    code: 5271,
  },
  {
    type: "Kabupaten",
    regency: "Maybrat",
    province_code: 92,
    code: 9210,
  },
  {
    type: "Kota",
    regency: "Medan",
    province_code: 12,
    code: 1271,
  },
  {
    type: "Kabupaten",
    regency: "Melawi",
    province_code: 61,
    code: 6110,
  },
  {
    type: "Kabupaten",
    regency: "Mempawah",
    province_code: 61,
    code: 6102,
  },
  {
    type: "Kabupaten",
    regency: "Merangin",
    province_code: 15,
    code: 1502,
  },
  {
    type: "Kabupaten",
    regency: "Merauke",
    province_code: 93,
    code: 9301,
  },
  {
    type: "Kabupaten",
    regency: "Mesuji",
    province_code: 18,
    code: 1811,
  },
  {
    type: "Kota",
    regency: "Metro",
    province_code: 18,
    code: 1872,
  },
  {
    type: "Kabupaten",
    regency: "Mimika",
    province_code: 94,
    code: 9404,
  },
  {
    type: "Kabupaten",
    regency: "Minahasa",
    province_code: 71,
    code: 7102,
  },
  {
    type: "Kabupaten",
    regency: "Minahasa Selatan",
    province_code: 71,
    code: 7105,
  },
  {
    type: "Kabupaten",
    regency: "Minahasa Tenggara",
    province_code: 71,
    code: 7107,
  },
  {
    type: "Kabupaten",
    regency: "Minahasa Utara",
    province_code: 71,
    code: 7106,
  },
  {
    type: "Kabupaten",
    regency: "Mojokerto",
    province_code: 35,
    code: 3516,
  },
  {
    type: "Kota",
    regency: "Mojokerto",
    province_code: 35,
    code: 3576,
  },
  {
    type: "Kabupaten",
    regency: "Morowali",
    province_code: 72,
    code: 7206,
  },
  {
    type: "Kabupaten",
    regency: "Morowali Utara",
    province_code: 72,
    code: 7212,
  },
  {
    type: "Kabupaten",
    regency: "Muara Enim",
    province_code: 16,
    code: 1603,
  },
  {
    type: "Kabupaten",
    regency: "Muaro Jambi",
    province_code: 15,
    code: 1505,
  },
  {
    type: "Kabupaten",
    regency: "Muko Muko",
    province_code: 17,
    code: 1706,
  },
  {
    type: "Kabupaten",
    regency: "Muna",
    province_code: 74,
    code: 7403,
  },
  {
    type: "Kabupaten",
    regency: "Muna Barat",
    province_code: 74,
    code: 7413,
  },
  {
    type: "Kabupaten",
    regency: "Murung Raya",
    province_code: 62,
    code: 6212,
  },
  {
    type: "Kabupaten",
    regency: "Musi Banyuasin",
    province_code: 16,
    code: 1606,
  },
  {
    type: "Kabupaten",
    regency: "Musi Rawas",
    province_code: 16,
    code: 1605,
  },
  {
    type: "Kabupaten",
    regency: "Musi Rawas Utara",
    province_code: 16,
    code: 1613,
  },
  {
    type: "Kabupaten",
    regency: "Nabire",
    province_code: 94,
    code: 9401,
  },
  {
    type: "Kabupaten",
    regency: "Nagan Raya",
    province_code: 11,
    code: 1115,
  },
  {
    type: "Kabupaten",
    regency: "Nagekeo",
    province_code: 53,
    code: 5316,
  },
  {
    type: "Kabupaten",
    regency: "Natuna",
    province_code: 21,
    code: 2103,
  },
  {
    type: "Kabupaten",
    regency: "Nduga",
    province_code: 95,
    code: 9508,
  },
  {
    type: "Kabupaten",
    regency: "Ngada",
    province_code: 53,
    code: 5309,
  },
  {
    type: "Kabupaten",
    regency: "Nganjuk",
    province_code: 35,
    code: 3518,
  },
  {
    type: "Kabupaten",
    regency: "Ngawi",
    province_code: 35,
    code: 3521,
  },
  {
    type: "Kabupaten",
    regency: "Nias",
    province_code: 12,
    code: 1204,
  },
  {
    type: "Kabupaten",
    regency: "Nias Barat",
    province_code: 12,
    code: 1225,
  },
  {
    type: "Kabupaten",
    regency: "Nias Selatan",
    province_code: 12,
    code: 1214,
  },
  {
    type: "Kabupaten",
    regency: "Nias Utara",
    province_code: 12,
    code: 1224,
  },
  {
    type: "Kabupaten",
    regency: "Nunukan",
    province_code: 65,
    code: 6503,
  },
  {
    type: "Kabupaten",
    regency: "Ogan Ilir",
    province_code: 16,
    code: 1610,
  },
  {
    type: "Kabupaten",
    regency: "Ogan Komering Ilir",
    province_code: 16,
    code: 1602,
  },
  {
    type: "Kabupaten",
    regency: "Ogan Komering Ulu",
    province_code: 16,
    code: 1601,
  },
  {
    type: "Kabupaten",
    regency: "Ogan Komering Ulu Selatan",
    province_code: 16,
    code: 1609,
  },
  {
    type: "Kabupaten",
    regency: "Ogan Komering Ulu Timur",
    province_code: 16,
    code: 1608,
  },
  {
    type: "Kabupaten",
    regency: "Pacitan",
    province_code: 35,
    code: 3501,
  },
  {
    type: "Kota",
    regency: "Padang",
    province_code: 13,
    code: 1371,
  },
  {
    type: "Kabupaten",
    regency: "Padang Lawas",
    province_code: 12,
    code: 1221,
  },
  {
    type: "Kabupaten",
    regency: "Padang Lawas Utara",
    province_code: 12,
    code: 1220,
  },
  {
    type: "Kota",
    regency: "Padang Panjang",
    province_code: 13,
    code: 1374,
  },
  {
    type: "Kabupaten",
    regency: "Padang Pariaman",
    province_code: 13,
    code: 1305,
  },
  {
    type: "Kota",
    regency: "Padangsidimpuan",
    province_code: 12,
    code: 1277,
  },
  {
    type: "Kota",
    regency: "Pagar Alam",
    province_code: 16,
    code: 1672,
  },
  {
    type: "Kabupaten",
    regency: "Pahuwato",
    province_code: 75,
    code: 7504,
  },
  {
    type: "Kabupaten",
    regency: "Pakpak Bharat",
    province_code: 12,
    code: 1215,
  },
  {
    type: "Kota",
    regency: "Palangkaraya",
    province_code: 62,
    code: 6271,
  },
  {
    type: "Kota",
    regency: "Palembang",
    province_code: 16,
    code: 1671,
  },
  {
    type: "Kota",
    regency: "Palopo",
    province_code: 73,
    code: 7373,
  },
  {
    type: "Kota",
    regency: "Palu",
    province_code: 72,
    code: 7271,
  },
  {
    type: "Kabupaten",
    regency: "Pamekasan",
    province_code: 35,
    code: 3528,
  },
  {
    type: "Kabupaten",
    regency: "Pandeglang",
    province_code: 36,
    code: 3601,
  },
  {
    type: "Kabupaten",
    regency: "Pangandaran",
    province_code: 32,
    code: 3218,
  },
  {
    type: "Kabupaten",
    regency: "Pangkajene Kepulauan",
    province_code: 73,
    code: 7310,
  },
  {
    type: "Kota",
    regency: "Pangkal Pinang",
    province_code: 19,
    code: 1971,
  },
  {
    type: "Kabupaten",
    regency: "Paniai",
    province_code: 94,
    code: 9403,
  },
  {
    type: "Kota",
    regency: "Pare Pare",
    province_code: 73,
    code: 7372,
  },
  {
    type: "Kota",
    regency: "Pariaman",
    province_code: 13,
    code: 1377,
  },
  {
    type: "Kabupaten",
    regency: "Parigi Moutong",
    province_code: 72,
    code: 7208,
  },
  {
    type: "Kabupaten",
    regency: "Pasaman",
    province_code: 13,
    code: 1308,
  },
  {
    type: "Kabupaten",
    regency: "Pasaman Barat",
    province_code: 13,
    code: 1312,
  },
  {
    type: "Kabupaten",
    regency: "Pasangkayu (Mamuju Utara)",
    province_code: 76,
    code: 7601,
  },
  {
    type: "Kabupaten",
    regency: "Paser",
    province_code: 64,
    code: 6401,
  },
  {
    type: "Kabupaten",
    regency: "Pasuruan",
    province_code: 35,
    code: 3514,
  },
  {
    type: "Kota",
    regency: "Pasuruan",
    province_code: 35,
    code: 3575,
  },
  {
    type: "Kabupaten",
    regency: "Pati",
    province_code: 33,
    code: 3318,
  },
  {
    type: "Kota",
    regency: "Payakumbuh",
    province_code: 13,
    code: 1376,
  },
  {
    type: "Kabupaten",
    regency: "Pegunungan Arfak",
    province_code: 92,
    code: 9212,
  },
  {
    type: "Kabupaten",
    regency: "Pegunungan Bintang",
    province_code: 95,
    code: 9502,
  },
  {
    type: "Kabupaten",
    regency: "Pekalongan",
    province_code: 33,
    code: 3326,
  },
  {
    type: "Kota",
    regency: "Pekalongan",
    province_code: 33,
    code: 3375,
  },
  {
    type: "Kota",
    regency: "Pekanbaru",
    province_code: 14,
    code: 1471,
  },
  {
    type: "Kabupaten",
    regency: "Pelalawan",
    province_code: 14,
    code: 1405,
  },
  {
    type: "Kabupaten",
    regency: "Pemalang",
    province_code: 33,
    code: 3327,
  },
  {
    type: "Kota",
    regency: "Pematangsiantar",
    province_code: 12,
    code: 1272,
  },
  {
    type: "Kabupaten",
    regency: "Penajam Paser Utara",
    province_code: 64,
    code: 6409,
  },
  {
    type: "Kabupaten",
    regency: "Penukal Abab Lematang Ilir",
    province_code: 16,
    code: 1612,
  },
  {
    type: "Kabupaten",
    regency: "Pesawaran",
    province_code: 18,
    code: 1809,
  },
  {
    type: "Kabupaten",
    regency: "Pesisir Barat",
    province_code: 18,
    code: 1813,
  },
  {
    type: "Kabupaten",
    regency: "Pesisir Selatan",
    province_code: 13,
    code: 1301,
  },
  {
    type: "Kabupaten",
    regency: "Pidie",
    province_code: 11,
    code: 1107,
  },
  {
    type: "Kabupaten",
    regency: "Pidie Jaya",
    province_code: 11,
    code: 1118,
  },
  {
    type: "Kabupaten",
    regency: "Pinrang",
    province_code: 73,
    code: 7315,
  },
  {
    type: "Kabupaten",
    regency: "Polewali Mandar",
    province_code: 76,
    code: 7604,
  },
  {
    type: "Kabupaten",
    regency: "Ponorogo",
    province_code: 35,
    code: 3502,
  },
  {
    type: "Kota",
    regency: "Pontianak",
    province_code: 61,
    code: 6171,
  },
  {
    type: "Kabupaten",
    regency: "Poso",
    province_code: 72,
    code: 7202,
  },
  {
    type: "Kota",
    regency: "Prabumulih",
    province_code: 16,
    code: 1674,
  },
  {
    type: "Kabupaten",
    regency: "Pringsewu",
    province_code: 18,
    code: 1810,
  },
  {
    type: "Kabupaten",
    regency: "Probolinggo",
    province_code: 35,
    code: 3513,
  },
  {
    type: "Kota",
    regency: "Probolinggo",
    province_code: 35,
    code: 3574,
  },
  {
    type: "Kabupaten",
    regency: "Pulang Pisau",
    province_code: 62,
    code: 6211,
  },
  {
    type: "Kabupaten",
    regency: "Pulau Morotai",
    province_code: 82,
    code: 8207,
  },
  {
    type: "Kabupaten",
    regency: "Pulau Taliabu",
    province_code: 82,
    code: 8208,
  },
  {
    type: "Kabupaten",
    regency: "Puncak",
    province_code: 94,
    code: 9405,
  },
  {
    type: "Kabupaten",
    regency: "Puncak Jaya",
    province_code: 94,
    code: 9402,
  },
  {
    type: "Kabupaten",
    regency: "Purbalingga",
    province_code: 33,
    code: 3303,
  },
  {
    type: "Kabupaten",
    regency: "Purwakarta",
    province_code: 32,
    code: 3214,
  },
  {
    type: "Kabupaten",
    regency: "Purworejo",
    province_code: 33,
    code: 3306,
  },
  {
    type: "Kabupaten",
    regency: "Raja Ampat",
    province_code: 92,
    code: 9205,
  },
  {
    type: "Kabupaten",
    regency: "Rejang Lebong",
    province_code: 17,
    code: 1702,
  },
  {
    type: "Kabupaten",
    regency: "Rembang",
    province_code: 33,
    code: 3317,
  },
  {
    type: "Kabupaten",
    regency: "Rokan Hilir",
    province_code: 14,
    code: 1407,
  },
  {
    type: "Kabupaten",
    regency: "Rokan Hulu",
    province_code: 14,
    code: 1406,
  },
  {
    type: "Kabupaten",
    regency: "Rote Ndao",
    province_code: 53,
    code: 5314,
  },
  {
    type: "Kota",
    regency: "Sabang",
    province_code: 11,
    code: 1172,
  },
  {
    type: "Kabupaten",
    regency: "Sabu Raijua",
    province_code: 53,
    code: 5320,
  },
  {
    type: "Kota",
    regency: "Salatiga",
    province_code: 33,
    code: 3373,
  },
  {
    type: "Kota",
    regency: "Samarinda",
    province_code: 64,
    code: 6472,
  },
  {
    type: "Kabupaten",
    regency: "Sambas",
    province_code: 61,
    code: 6101,
  },
  {
    type: "Kabupaten",
    regency: "Samosir",
    province_code: 12,
    code: 1217,
  },
  {
    type: "Kabupaten",
    regency: "Sampang",
    province_code: 35,
    code: 3527,
  },
  {
    type: "Kabupaten",
    regency: "Sanggau",
    province_code: 61,
    code: 6103,
  },
  {
    type: "Kabupaten",
    regency: "Sarmi",
    province_code: 91,
    code: 9110,
  },
  {
    type: "Kabupaten",
    regency: "Sarolangun",
    province_code: 15,
    code: 1503,
  },
  {
    type: "Kota",
    regency: "Sawahlunto",
    province_code: 13,
    code: 1373,
  },
  {
    type: "Kabupaten",
    regency: "Sekadau",
    province_code: 61,
    code: 6109,
  },
  {
    type: "Kabupaten",
    regency: "Seluma",
    province_code: 17,
    code: 1705,
  },
  {
    type: "Kabupaten",
    regency: "Semarang",
    province_code: 33,
    code: 3322,
  },
  {
    type: "Kota",
    regency: "Semarang",
    province_code: 33,
    code: 3374,
  },
  {
    type: "Kabupaten",
    regency: "Seram Bagian Barat",
    province_code: 81,
    code: 8106,
  },
  {
    type: "Kabupaten",
    regency: "Seram Bagian Timur",
    province_code: 81,
    code: 8105,
  },
  {
    type: "Kota",
    regency: "Serang",
    province_code: 36,
    code: 3673,
  },
  {
    type: "Kabupaten",
    regency: "Serang",
    province_code: 36,
    code: 3604,
  },
  {
    type: "Kabupaten",
    regency: "Serdang Bedagai",
    province_code: 12,
    code: 1218,
  },
  {
    type: "Kabupaten",
    regency: "Seruyan",
    province_code: 62,
    code: 6207,
  },
  {
    type: "Kabupaten",
    regency: "Siak",
    province_code: 14,
    code: 1408,
  },
  {
    type: "Kota",
    regency: "Sibolga",
    province_code: 12,
    code: 1273,
  },
  {
    type: "Kabupaten",
    regency: "Sidenreng Rappang",
    province_code: 73,
    code: 7314,
  },
  {
    type: "Kabupaten",
    regency: "Sidoarjo",
    province_code: 35,
    code: 3515,
  },
  {
    type: "Kabupaten",
    regency: "Sigi",
    province_code: 72,
    code: 7210,
  },
  {
    type: "Kabupaten",
    regency: "Sijunjung",
    province_code: 13,
    code: 1303,
  },
  {
    type: "Kabupaten",
    regency: "Sikka",
    province_code: 53,
    code: 5307,
  },
  {
    type: "Kabupaten",
    regency: "Simalungun",
    province_code: 12,
    code: 1208,
  },
  {
    type: "Kabupaten",
    regency: "Simeulue",
    province_code: 11,
    code: 1109,
  },
  {
    type: "Kota",
    regency: "Singkawang",
    province_code: 61,
    code: 6172,
  },
  {
    type: "Kabupaten",
    regency: "Sinjai",
    province_code: 73,
    code: 7307,
  },
  {
    type: "Kabupaten",
    regency: "Sintang",
    province_code: 61,
    code: 6105,
  },
  {
    type: "Kabupaten",
    regency: "Situbondo",
    province_code: 35,
    code: 3512,
  },
  {
    type: "Kabupaten",
    regency: "Sleman",
    province_code: 34,
    code: 3404,
  },
  {
    type: "Kabupaten",
    regency: "Solok",
    province_code: 13,
    code: 1302,
  },
  {
    type: "Kota",
    regency: "Solok",
    province_code: 13,
    code: 1372,
  },
  {
    type: "Kabupaten",
    regency: "Solok Selatan",
    province_code: 13,
    code: 1311,
  },
  {
    type: "Kabupaten",
    regency: "Soppeng",
    province_code: 73,
    code: 7312,
  },
  {
    type: "Kabupaten",
    regency: "Sorong",
    province_code: 92,
    code: 9201,
  },
  {
    type: "Kota",
    regency: "Sorong",
    province_code: 92,
    code: 9271,
  },
  {
    type: "Kabupaten",
    regency: "Sorong Selatan",
    province_code: 92,
    code: 9204,
  },
  {
    type: "Kabupaten",
    regency: "Sragen",
    province_code: 33,
    code: 3314,
  },
  {
    type: "Kabupaten",
    regency: "Subang",
    province_code: 32,
    code: 3213,
  },
  {
    type: "Kota",
    regency: "Subulussalam",
    province_code: 11,
    code: 1175,
  },
  {
    type: "Kota",
    regency: "Sukabumi",
    province_code: 32,
    code: 3272,
  },
  {
    type: "Kabupaten",
    regency: "Sukabumi",
    province_code: 32,
    code: 3202,
  },
  {
    type: "Kabupaten",
    regency: "Sukamara",
    province_code: 62,
    code: 6208,
  },
  {
    type: "Kabupaten",
    regency: "Sukoharjo",
    province_code: 33,
    code: 3311,
  },
  {
    type: "Kabupaten",
    regency: "Sumba Barat",
    province_code: 53,
    code: 5312,
  },
  {
    type: "Kabupaten",
    regency: "Sumba Barat Daya",
    province_code: 53,
    code: 5318,
  },
  {
    type: "Kabupaten",
    regency: "Sumba Tengah",
    province_code: 53,
    code: 5317,
  },
  {
    type: "Kabupaten",
    regency: "Sumba Timur",
    province_code: 53,
    code: 5311,
  },
  {
    type: "Kabupaten",
    regency: "Sumbawa",
    province_code: 52,
    code: 5204,
  },
  {
    type: "Kabupaten",
    regency: "Sumbawa Barat",
    province_code: 52,
    code: 5207,
  },
  {
    type: "Kabupaten",
    regency: "Sumedang",
    province_code: 32,
    code: 3211,
  },
  {
    type: "Kabupaten",
    regency: "Sumenep",
    province_code: 35,
    code: 3529,
  },
  {
    type: "Kota",
    regency: "Sungai Penuh",
    province_code: 15,
    code: 1572,
  },
  {
    type: "Kabupaten",
    regency: "Supiori",
    province_code: 91,
    code: 9119,
  },
  {
    type: "Kota",
    regency: "Surabaya",
    province_code: 35,
    code: 3578,
  },
  {
    type: "Kota",
    regency: "Surakarta",
    province_code: 33,
    code: 3372,
  },
  {
    type: "Kabupaten",
    regency: "Tabalong",
    province_code: 63,
    code: 6309,
  },
  {
    type: "Kabupaten",
    regency: "Tabanan",
    province_code: 51,
    code: 5102,
  },
  {
    type: "Kabupaten",
    regency: "Takalar",
    province_code: 73,
    code: 7305,
  },
  {
    type: "Kabupaten",
    regency: "Tambrauw",
    province_code: 92,
    code: 9209,
  },
  {
    type: "Kabupaten",
    regency: "Tana Tidung",
    province_code: 65,
    code: 6504,
  },
  {
    type: "Kabupaten",
    regency: "Tana Toraja",
    province_code: 73,
    code: 7318,
  },
  {
    type: "Kabupaten",
    regency: "Tanah Bumbu",
    province_code: 63,
    code: 6310,
  },
  {
    type: "Kabupaten",
    regency: "Tanah Datar",
    province_code: 13,
    code: 1304,
  },
  {
    type: "Kabupaten",
    regency: "Tanah Laut",
    province_code: 63,
    code: 6301,
  },
  {
    type: "Kota",
    regency: "Tangerang",
    province_code: 36,
    code: 3671,
  },
  {
    type: "Kabupaten",
    regency: "Tangerang",
    province_code: 36,
    code: 3603,
  },
  {
    type: "Kota",
    regency: "Tangerang Selatan",
    province_code: 36,
    code: 3674,
  },
  {
    type: "Kabupaten",
    regency: "Tanggamus",
    province_code: 18,
    code: 1806,
  },
  {
    type: "Kota",
    regency: "Tanjung Balai",
    province_code: 12,
    code: 1274,
  },
  {
    type: "Kabupaten",
    regency: "Tanjung Jabung Barat",
    province_code: 15,
    code: 1506,
  },
  {
    type: "Kabupaten",
    regency: "Tanjung Jabung Timur",
    province_code: 15,
    code: 1507,
  },
  {
    type: "Kota",
    regency: "Tanjung Pinang",
    province_code: 21,
    code: 2172,
  },
  {
    type: "Kabupaten",
    regency: "Tapanuli Selatan",
    province_code: 12,
    code: 1203,
  },
  {
    type: "Kabupaten",
    regency: "Tapanuli Tengah",
    province_code: 12,
    code: 1201,
  },
  {
    type: "Kabupaten",
    regency: "Tapanuli Utara",
    province_code: 12,
    code: 1202,
  },
  {
    type: "Kabupaten",
    regency: "Tapin",
    province_code: 63,
    code: 6305,
  },
  {
    type: "Kota",
    regency: "Tarakan",
    province_code: 65,
    code: 6571,
  },
  {
    type: "Kota",
    regency: "Tasikmalaya",
    province_code: 32,
    code: 3278,
  },
  {
    type: "Kabupaten",
    regency: "Tasikmalaya",
    province_code: 32,
    code: 3206,
  },
  {
    type: "Kota",
    regency: "Tebing Tinggi",
    province_code: 12,
    code: 1276,
  },
  {
    type: "Kabupaten",
    regency: "Tebo",
    province_code: 15,
    code: 1509,
  },
  {
    type: "Kabupaten",
    regency: "Tegal",
    province_code: 33,
    code: 3328,
  },
  {
    type: "Kota",
    regency: "Tegal",
    province_code: 33,
    code: 3376,
  },
  {
    type: "Kabupaten",
    regency: "Teluk Bintuni",
    province_code: 92,
    code: 9206,
  },
  {
    type: "Kabupaten",
    regency: "Teluk Wondama",
    province_code: 92,
    code: 9207,
  },
  {
    type: "Kabupaten",
    regency: "Temanggung",
    province_code: 33,
    code: 3323,
  },
  {
    type: "Kota",
    regency: "Ternate",
    province_code: 82,
    code: 8271,
  },
  {
    type: "Kota",
    regency: "Tidore Kepulauan",
    province_code: 82,
    code: 8272,
  },
  {
    type: "Kabupaten",
    regency: "Timor Tengah Selatan",
    province_code: 53,
    code: 5302,
  },
  {
    type: "Kabupaten",
    regency: "Timor Tengah Utara",
    province_code: 53,
    code: 5303,
  },
  {
    type: "Kabupaten",
    regency: "Toba",
    province_code: 12,
    code: 1212,
  },
  {
    type: "Kabupaten",
    regency: "Tojo Una Una",
    province_code: 72,
    code: 7209,
  },
  {
    type: "Kabupaten",
    regency: "Toli Toli",
    province_code: 72,
    code: 7204,
  },
  {
    type: "Kabupaten",
    regency: "Tolikara",
    province_code: 95,
    code: 9504,
  },
  {
    type: "Kota",
    regency: "Tomohon",
    province_code: 71,
    code: 7173,
  },
  {
    type: "Kabupaten",
    regency: "Toraja Utara",
    province_code: 73,
    code: 7326,
  },
  {
    type: "Kabupaten",
    regency: "Trenggalek",
    province_code: 35,
    code: 3503,
  },
  {
    type: "Kota",
    regency: "Tual",
    province_code: 81,
    code: 8172,
  },
  {
    type: "Kabupaten",
    regency: "Tuban",
    province_code: 35,
    code: 3523,
  },
  {
    type: "Kabupaten",
    regency: "Tulang Bawang",
    province_code: 18,
    code: 1805,
  },
  {
    type: "Kabupaten",
    regency: "Tulang Bawang Barat",
    province_code: 18,
    code: 1812,
  },
  {
    type: "Kabupaten",
    regency: "Tulungagung",
    province_code: 35,
    code: 3504,
  },
  {
    type: "Kabupaten",
    regency: "Wajo",
    province_code: 73,
    code: 7313,
  },
  {
    type: "Kabupaten",
    regency: "Wakatobi",
    province_code: 74,
    code: 7407,
  },
  {
    type: "Kabupaten",
    regency: "Waropen",
    province_code: 91,
    code: 9115,
  },
  {
    type: "Kabupaten",
    regency: "Way Kanan",
    province_code: 18,
    code: 1808,
  },
  {
    type: "Kabupaten",
    regency: "Wonogiri",
    province_code: 33,
    code: 3312,
  },
  {
    type: "Kabupaten",
    regency: "Wonosobo",
    province_code: 33,
    code: 3307,
  },
  {
    type: "Kabupaten",
    regency: "Yahukimo",
    province_code: 95,
    code: 9503,
  },
  {
    type: "Kabupaten",
    regency: "Yalimo",
    province_code: 95,
    code: 9506,
  },
  {
    type: "Kota",
    regency: "Yogyakarta",
    province_code: 34,
    code: 3471,
  },
];
